### ISSUE TITLE
Model Training

### ISSUE THREAD

**Issue by imdsafi09** [nicofretti/anomaly-detection#1]
Hi, 

Thank you for open-sourcing your work. I would like to train the proposed model on my own similar dataset. Could you please explain how to train the model? Thank you.

**Comment by nicofretti** [comment]
Please provide me with your personal email. I would like to share the project documentation 💯 
(mine: nico.fretti@gmail.com)

**Comment by imdsafi09** [comment]
Thank you for your prompt response. I already sent you an email, but if you did not receive it, here is my email: (imadsafi08@gmail.com).

regards,

**Comment by imdsafi09** [comment]
Thank you for your prompt response. I already sent you an email, but if you did not receive it, here is my email: (imadsafi08@gmail.com).

regards,
